# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{cantango-core}
  s.version = "1.0.0.beta1"

  s.required_rubygems_version = Gem::Requirement.new("> 1.3.1") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Kristian Mandrup}, %q{Stanislaw Pankevich}]
  s.date = %q{2011-11-24}
  s.description = %q{Define your permission rules as role- or role group specific permits.
Integrates well with multiple Devise user acounts.
Includes rules caching.
Store permissions in yaml file or key-value store}
  s.email = %q{kmandrup@gmail.com, s.pankevich@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.mdown"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.mdown",
    "Rakefile",
    "VERSION",
    "cantango-core.gemspec",
    "lib/cantango/ability.rb",
    "lib/cantango/ability/base.rb",
    "lib/cantango/ability/cache.rb",
    "lib/cantango/ability/cache/key.rb",
    "lib/cantango/ability/cached.rb",
    "lib/cantango/ability/executor.rb",
    "lib/cantango/ability/executor/base.rb",
    "lib/cantango/ability/executor/cached.rb",
    "lib/cantango/ability/executor/modes.rb",
    "lib/cantango/ability/executor/non_cached.rb",
    "lib/cantango/ability/helper.rb",
    "lib/cantango/ability/helper/account.rb",
    "lib/cantango/ability/helper/engine.rb",
    "lib/cantango/ability/helper/role.rb",
    "lib/cantango/ability/helper/role_group.rb",
    "lib/cantango/ability/helper/user.rb",
    "lib/cantango/cancan/rule.rb",
    "lib/cantango/core.rb",
    "lib/cantango/engine.rb",
    "lib/cantango/filter.rb",
    "lib/cantango/filter/base.rb",
    "lib/cantango/filter/role.rb",
    "lib/cantango/filter/role_group.rb",
    "lib/cantango/helpers.rb",
    "lib/cantango/helpers/debug.rb",
    "lib/cantango/helpers/role.rb",
    "lib/cantango/helpers/role_group.rb",
    "lib/cantango/loader.rb",
    "lib/cantango/loader/yaml.rb",
    "lib/cantango/macros.rb",
    "lib/cantango/macros/account.rb",
    "lib/cantango/macros/user.rb",
    "lib/cantango/model.rb",
    "lib/cantango/model/guest.rb",
    "lib/cantango/rails.rb",
    "lib/cantango/rails/engine.rb",
    "lib/cantango/rails/helpers/base_helper.rb",
    "lib/cantango/rails/helpers/controller_helper.rb",
    "lib/cantango/rails/helpers/rest_helper.rb",
    "lib/cantango/rails/helpers/view_helper.rb",
    "lib/cantango/rails/railtie.rb",
    "lib/cantango/rspec.rb",
    "lib/cantango/rspec/config.rb",
    "lib/cantango/rspec/matchers.rb",
    "lib/cantango/rspec/matchers/be_allowed_to.rb",
    "lib/cantango/rules.rb",
    "lib/cantango/rules/adaptor.rb",
    "lib/cantango/rules/adaptor/active_record.rb",
    "lib/cantango/rules/adaptor/data_mapper.rb",
    "lib/cantango/rules/adaptor/generic.rb",
    "lib/cantango/rules/adaptor/mongo.rb",
    "lib/cantango/rules/adaptor/mongo_mapper.rb",
    "lib/cantango/rules/adaptor/mongoid.rb",
    "lib/cantango/rules/adaptor/relational.rb",
    "lib/cantango/rules/dsl.rb",
    "lib/cantango/rules/rule_class.rb",
    "lib/cantango/rules/scope.rb",
    "lib/cantango/rules/user_relation.rb",
    "lib/cantango/scope.rb",
    "lib/cantango/scope/ability.rb",
    "lib/generators/cantango/install/install_generator.rb",
    "lib/generators/cantango/install/templates/cantango.rb",
    "lib/generators/cantango/install/templates/categories.yml",
    "lib/generators/cantango/install/templates/permissions.yml",
    "spec/cantango-core_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/kristianmandrup/cantango}
  s.licenses = [%q{MIT}]
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.6}
  s.summary = %q{CanCan extension with role oriented permission management and more}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, [">= 3.0.1"])
      s.add_runtime_dependency(%q<cancan>, [">= 1.4"])
      s.add_runtime_dependency(%q<sugar-high>, [">= 0.6.0"])
      s.add_runtime_dependency(%q<sweetloader>, ["~> 0.1.0"])
      s.add_runtime_dependency(%q<hashie>, [">= 0"])
      s.add_development_dependency(%q<rspec-rails>, [">= 2.6.1"])
      s.add_development_dependency(%q<forgery>, [">= 0.3"])
      s.add_development_dependency(%q<factory_girl>, [">= 0"])
      s.add_development_dependency(%q<sqlite3>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 2.6.0"])
      s.add_development_dependency(%q<jeweler>, [">= 1.6.4"])
      s.add_development_dependency(%q<bundler>, [">= 1.1.rc"])
      s.add_development_dependency(%q<rdoc>, [">= 0"])
      s.add_development_dependency(%q<rake>, [">= 0.9.2.2"])
    else
      s.add_dependency(%q<rails>, [">= 3.0.1"])
      s.add_dependency(%q<cancan>, [">= 1.4"])
      s.add_dependency(%q<sugar-high>, [">= 0.6.0"])
      s.add_dependency(%q<sweetloader>, ["~> 0.1.0"])
      s.add_dependency(%q<hashie>, [">= 0"])
      s.add_dependency(%q<rspec-rails>, [">= 2.6.1"])
      s.add_dependency(%q<forgery>, [">= 0.3"])
      s.add_dependency(%q<factory_girl>, [">= 0"])
      s.add_dependency(%q<sqlite3>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 2.6.0"])
      s.add_dependency(%q<jeweler>, [">= 1.6.4"])
      s.add_dependency(%q<bundler>, [">= 1.1.rc"])
      s.add_dependency(%q<rdoc>, [">= 0"])
      s.add_dependency(%q<rake>, [">= 0.9.2.2"])
    end
  else
    s.add_dependency(%q<rails>, [">= 3.0.1"])
    s.add_dependency(%q<cancan>, [">= 1.4"])
    s.add_dependency(%q<sugar-high>, [">= 0.6.0"])
    s.add_dependency(%q<sweetloader>, ["~> 0.1.0"])
    s.add_dependency(%q<hashie>, [">= 0"])
    s.add_dependency(%q<rspec-rails>, [">= 2.6.1"])
    s.add_dependency(%q<forgery>, [">= 0.3"])
    s.add_dependency(%q<factory_girl>, [">= 0"])
    s.add_dependency(%q<sqlite3>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 2.6.0"])
    s.add_dependency(%q<jeweler>, [">= 1.6.4"])
    s.add_dependency(%q<bundler>, [">= 1.1.rc"])
    s.add_dependency(%q<rdoc>, [">= 0"])
    s.add_dependency(%q<rake>, [">= 0.9.2.2"])
  end
end

